// ref:- https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
const keyMap: any = {
  // Control Keys
  8: "Backspace",
  9: "Tab",
  13: "Enter",
  16: "Shift",
  160: "Shift",
  161: "Shift",
  17: "Control",
  162: "Control",
  163: "Control",
  18: "Alt",
  164: "Alt",
  165: "Alternate Graphic",
  20: "CapsLock",
  27: "Escape",
  32: "Space",
  35: "End",
  36: "Home",
  33: "Page Up",
  34: "Page Down",
  37: "ArrowLeft",
  38: "ArrowUp",
  39: "ArrowRight",
  40: "ArrowDown",
  45: "Insert",
  46: "Delete",
  91: "Window",
  93: "Menu",
  144: "Num Lock",

  // Function Keys
  112: "F1",
  113: "F2",
  114: "F3",
  115: "F4",
  116: "F5",
  117: "F6",
  118: "F7",
  119: "F8",
  120: "F9",
  121: "F10",
  122: "F11",
  123: "F12",

  // Multimedia Keys
  173: "Mute",
  174: "Volume Up",
  175: "Volume Down",

  // Number row keys with Shift mappings
  48: { normal: "0", shift: ")" },
  49: { normal: "1", shift: "!" },
  50: { normal: "2", shift: "@" },
  51: { normal: "3", shift: "#" },
  52: { normal: "4", shift: "$" },
  53: { normal: "5", shift: "%" },
  54: { normal: "6", shift: "^" },
  55: { normal: "7", shift: "&" },
  56: { normal: "8", shift: "*" },
  57: { normal: "9", shift: "(" },

  // Alphabet Keys
  65: { normal: "a", shift: "A" },
  66: { normal: "b", shift: "B" },
  67: { normal: "c", shift: "C" },
  68: { normal: "d", shift: "D" },
  69: { normal: "e", shift: "E" },
  70: { normal: "f", shift: "F" },
  71: { normal: "g", shift: "G" },
  72: { normal: "h", shift: "H" },
  73: { normal: "i", shift: "I" },
  74: { normal: "j", shift: "J" },
  75: { normal: "k", shift: "K" },
  76: { normal: "l", shift: "L" },
  77: { normal: "m", shift: "M" },
  78: { normal: "n", shift: "N" },
  79: { normal: "o", shift: "O" },
  80: { normal: "p", shift: "P" },
  81: { normal: "q", shift: "Q" },
  82: { normal: "r", shift: "R" },
  83: { normal: "s", shift: "S" },
  84: { normal: "t", shift: "T" },
  85: { normal: "u", shift: "U" },
  86: { normal: "v", shift: "V" },
  87: { normal: "w", shift: "W" },
  88: { normal: "x", shift: "X" },
  89: { normal: "y", shift: "Y" },
  90: { normal: "z", shift: "Z" },

  // Punctuation & Special Characters
  186: { normal: ";", shift: ":" },
  187: { normal: "=", shift: "+" },
  188: { normal: ",", shift: "<" },
  189: { normal: "-", shift: "_" },
  190: { normal: ".", shift: ">" },
  191: { normal: "/", shift: "?" },
  192: { normal: "`", shift: "~" },
  219: { normal: "[", shift: "{" },
  220: { normal: "\\", shift: "|" },
  221: { normal: "]", shift: "}" },
  222: { normal: "'", shift: '"' },
};

export default keyMap;
